[package]
name = "ignite-teleprompter"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.35"
clipboard = "0.5.0"
eframe = "0.27.0"
egui = { version = "0.27.0", features = ["serde"]}
local-ip-address = "0.6.1"
serde = { version = "1.0.197", features = ["derive"]}
serde_json = "1.0.115"
tungstenite = "0.21.0"
web_server = "0.4.2"
