name: Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  # Allow manually triggering the workflow from the web UI.
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Install Linux and Windows Cross Compilers
      run: sudo apt-get install --yes --no-install-recommends musl-tools gcc-mingw-w64-x86-64-win32

    - name: Install Rustup targets
      run: rustup target add x86_64-unknown-linux-musl x86_64-pc-windows-gnu

    - name: Check out source code
      uses: actions/checkout@v3

    - name: Check
      run: cargo check

    - name: Build
      run: cargo build --target x86_64-unknown-linux-musl --target x86_64-pc-windows-gnu

    - name: Upload Binaries
      uses: actions/upload-artifact@v3
      with:
        name: binaries
        path: target